parameters:
    my_user_provider.class: AppBundle\Security\Core\User\MyFOSUBUserProvider

services:
    my.custom.user_provider:
        class:        AppBundle\Security\Core\User\MyFOSUBUserProvider
        arguments: ['@fos_user.user_manager', { github: github_id }]
